pretrained_model: null # pretrained TokenClassification model from list_available_models(), for example: NERModel
trainer:
  gpus: 1 # the number of gpus, 0 for CPU
  num_nodes: 1
  max_epochs: 10
  max_steps: null # precedence over max_epochs
  accumulate_grad_batches: 1 # accumulates grads every k batches
  gradient_clip_val: 1.0
  amp_level: O1 # O1/O2 for mixed precision
  precision: 16 # Should be set to 16 for O1 and O2, default is 16 as PT ignores it when am_level is O0
  accelerator: ddp
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 100  # Interval of logging.
  val_check_interval: 0.2 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  resume_from_checkpoint: null #/red/gatortron-phi/workspace/scripts/nemo_ner/results/i2b22014_345m_biomeg_530k/checkpoints/default-last.ckpt # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.

exp_manager:
  explicit_log_dir: ./i2b22010_345m_megatron # exp_dir for your experiment, if None, defaults to "./nemo_experiments"
  exp_dir: null
  name: null   # The name of your model
  version: null
  create_tensorboard_logger: true  # Whether you want exp_manger to create a tb logger
  create_checkpoint_callback: true  # Whether you want exp_manager to create a model checkpoint callback
  # checkpoint_callback_params:
  #   monitor: "val_loss"
  #   save_top_k: 10

model:
  nemo_path: ${exp_manager.explicit_log_dir}/default.nemo # filename to save the model and associated artifacts to .nemo file
  label_ids: null # will be filled during training
  dataset:
    data_dir: ./ner_datasets/nemo_ner_2010i2b2
    class_balancing: null # choose from [null, weighted_loss]. Weighted_loss enables the weighted class balancing of the loss, may be used for handling unbalanced classes
    max_seq_length: 512
    pad_label: 'O'
    ignore_extra_tokens: false
    ignore_start_end: false
    use_cache: true
    # shared among dataloaders
    num_workers: 8
    pin_memory: false
    drop_last: false

  train_ds:
    text_file: text_train.txt
    labels_file: labels_train.txt
    shuffle: true
    num_samples: -1
    batch_size: 8

  validation_ds:
    text_file: text_dev.txt
    labels_file: labels_dev.txt
    shuffle: false
    num_samples: -1
    batch_size: 8

  test_ds:
    text_file: text_test.txt
    labels_file: labels_test.txt
    shuffle: false
    num_samples: -1
    batch_size: 32
 
  tokenizer:
    tokenizer_name: ${model.language_model.pretrained_model_name} # or sentencepiece
    vocab_file: ./megatron_345m_cased/bert-large-cased-vocab.txt # path to vocab file
    tokenizer_model: null # only used if tokenizer is sentencepiece
    special_tokens: null

  language_model:
    pretrained_model_name: megatron-bert-cased
    lm_checkpoint: ./megatron_345m_cased/release/mp_rank_00/model_optim_rng.pt
    config_file: ./megatron_345m_cased/config.json # json file, precedence over config
    config: null

  head:
    num_fc_layers: 2
    fc_dropout: 0.1
    activation: 'relu'
    use_transformer_init: True

  optim:
    name: adamw
    lr: 1e-5
    weight_decay: 0.00

    sched:
      name: WarmupAnnealing
      # Scheduler params
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1

      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null